apiVersion: v1
kind: Pod
metadata:
  name: zonal-writer
  namespace: sanim-system
spec:
  serviceAccountName: sanim-initiator
  hostNetwork: true
  hostPID: true
  containers:
  - name: writer
    image: registry.access.redhat.com/ubi9/ubi:latest
    command:
    - /bin/bash
    - -c
    - |
      set -ex

      # Get node's zone
      NODE_IP=$(hostname -i | awk '{print $1}')
      ZONE=$(grep "^${NODE_IP}=" /etc/zone-map/mapping | cut -d= -f2 || echo "unknown")

      IQN="iqn.2020-05.com.thoughtexpo:storage:${ZONE}"

      # Find device for zonal IQN
      DEVICE=$(nsenter -t 1 -m -u -n -i /usr/sbin/iscsiadm -m session -P 3 | \
        awk -v iqn="$IQN" '
          /Target:/ { current_iqn=$2 }
          /Attached scsi disk/ && current_iqn==iqn { print "/dev/"$4; exit }
        ')

      if [ -z "$DEVICE" ]; then
        echo "No device found for IQN: $IQN"
        exit 1
      fi

      echo "Found device: $DEVICE for zone: $ZONE"

      # Format if not already formatted
      if ! blkid "$DEVICE" | grep -q ext4; then
        echo "Formatting $DEVICE as ext4..."
        mkfs.ext4 -F "$DEVICE"
      fi

      # Mount and write zone-specific data
      mkdir -p /mnt/zonal
      mount "$DEVICE" /mnt/zonal

      echo "Zone-isolated storage - written at $(date)" > /mnt/zonal/data.txt
      echo "Hostname: $(hostname)" >> /mnt/zonal/data.txt
      echo "Zone: $ZONE" >> /mnt/zonal/data.txt
      echo "IQN: $IQN" >> /mnt/zonal/data.txt

      cat /mnt/zonal/data.txt

      echo "=== Data written, keeping pod running ==="
      sleep 3600
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /dev
      mountPropagation: HostToContainer
    - name: zone-map
      mountPath: /etc/zone-map
      readOnly: true
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: zone-map
    configMap:
      name: node-zone-map
